In [1]:
import numpy as np

In [2]:
dir(np.random)

['BitGenerator',
 'Generator',
 'MT19937',
 'PCG64',
 'PCG64DXSM',
 'Philox',
 'RandomState',
 'SFC64',
 'SeedSequence',
 '__RandomState_ctor',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_bounded_integers',
 '_common',
 '_generator',
 '_mt19937',
 '_pcg64',
 '_philox',
 '_pickle',
 '_sfc64',
 'beta',
 'binomial',
 'bit_generator',
 'bytes',
 'chisquare',
 'choice',
 'default_rng',
 'dirichlet',
 'exponential',
 'f',
 'gamma',
 'geometric',
 'get_bit_generator',
 'get_state',
 'gumbel',
 'hypergeometric',
 'laplace',
 'logistic',
 'lognormal',
 'logseries',
 'mtrand',
 'multinomial',
 'multivariate_normal',
 'negative_binomial',
 'noncentral_chisquare',
 'noncentral_f',
 'normal',
 'pareto',
 'permutation',
 'poisson',
 'power',
 'rand',
 'randint',
 'randn',
 'random',
 'random_integers',
 'random_sample',
 'ranf',
 'rayleigh',
 'sample',
 'seed',
 'set_bit_generator',
 'set_state',
 'shuf

In [3]:
rng=np.random.default_rng()
a=rng.random(25)
print(a)
np.sum(a)

[0.44817068 0.40446465 0.61996097 0.46871129 0.66120421 0.33147879
 0.21090941 0.65301322 0.26228683 0.24675476 0.11768115 0.51333462
 0.65731431 0.16890638 0.64212116 0.74037965 0.23598217 0.57863041
 0.57793375 0.03203447 0.47584511 0.57196531 0.10031018 0.87870902
 0.23877899]


10.836881470222188

In [17]:
np.min(a)

0.08384253165849154

In [18]:
np.max(a)

0.9771339019096007

In [10]:
x=rng.integers(1,999,[5,5])
x

array([[766, 203, 626, 205, 242],
       [ 94, 921, 102, 737,  41],
       [ 11, 639, 299,  80, 449],
       [798, 720,   8, 776,  75],
       [262, 955, 578, 894, 607]], dtype=int64)

In [5]:
x.max(axis=1) #for rows

array([956, 792, 901, 757, 801], dtype=int64)

In [6]:
x.max(axis=0) #for columns

array([748, 801, 928, 956, 792], dtype=int64)

In [11]:
np.nanmax(x)

955