In [2]:
import numpy as np

In [5]:
np.zeros(10,dtype=str)

array(['', '', '', '', '', '', '', '', '', ''], dtype='<U1')

In [8]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
np.zeros(10,dtype=float)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [16]:
np.ones((4,4),dtype=float)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.full((5,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [20]:
np.arange(0,20,1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [22]:
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [24]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [26]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [34]:
np.linspace(0,360,13)

array([  0.,  30.,  60.,  90., 120., 150., 180., 210., 240., 270., 300.,
       330., 360.])

In [37]:
np.random.random((3,3))

array([[0.70766767, 0.31991307, 0.95790659],
       [0.33331396, 0.56269137, 0.03218435],
       [0.19299031, 0.83135188, 0.65093025]])

In [57]:
np.random.normal(0,1,(3,3))

array([[-0.25190856,  1.57314998, -2.40362776],
       [ 1.87565933, -2.27527493, -1.42337212],
       [ 0.74940692,  1.05396291, -0.59839432]])

In [59]:
np.random.randint(1,10,(5,5))

array([[8, 9, 3, 3, 8],
       [7, 7, 8, 8, 2],
       [7, 9, 1, 1, 6],
       [2, 8, 4, 4, 1],
       [4, 1, 2, 6, 7]])

In [5]:
np.eye(6,6,0,int)

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

In [92]:
np.empty(3)

array([8.16418567e-312, 0.00000000e+000, 2.28896038e+243])