In [2]:
import numpy as np

In [4]:
a=np.arange(3)
b=np.arange(9).reshape([3,3])
print(a,"\n",b)

[0 1 2] 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [6]:
a+b

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [6]:
x=np.arange(4)
y=np.arange(4)[:,np.newaxis]
print(x)
print(y)

[0 1 2 3]
[[0]
 [1]
 [2]
 [3]]


In [10]:
x+y

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [3]:
p=np.arange(4)
q=np.arange(5)
# print(p+q) raises error

In [13]:
M = np.ones((2, 3))
a = np.arange(3)
print(M)
print(a)
M+a

[[1. 1. 1.]
 [1. 1. 1.]]
[0 1 2]


array([[1., 2., 3.],
       [1., 2., 3.]])

In [14]:
a = np.arange(3).reshape((3, 1))
b = np.arange(3)
a+b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [4]:
M = np.ones((3, 2))
a = np.arange(3)
M+a

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

In [24]:
# centering an array
rng=np.random.default_rng(seed=1701)
x=rng.random(5)

In [25]:
x

array([0.4020733 , 0.30563311, 0.67668051, 0.15821208, 0.79247763])

In [23]:
xmean=x.mean(0)
xmean

0.4670153257690991

In [24]:
y=x-xmean
y

array([-0.06494203, -0.16138222,  0.20966519, -0.30880324,  0.3254623 ])

In [25]:
y.mean(0)

2.2204460492503132e-17