## Sorting Arrays

In [3]:
import random
arr=[random.randint(0,100) for _ in range(10)]
print(arr)
sorted(arr)

[92, 50, 31, 28, 37, 73, 72, 22, 5, 91]


[5, 22, 28, 31, 37, 50, 72, 73, 91, 92]

In [4]:
arr.sort()
arr

[5, 22, 28, 31, 37, 50, 72, 73, 91, 92]

In [5]:
sorted("hello")

['e', 'h', 'l', 'l', 'o']

In [6]:
import numpy as np

array=np.array([1,4,5,3,7])
np.sort(array)

array([1, 3, 4, 5, 7])

In [7]:
array2=np.array([2,5,6,7,4,3,1])
np.argsort(array2)

array([6, 0, 5, 4, 1, 2, 3], dtype=int64)

In [8]:
array2[np.argsort(array2)]

array([1, 2, 3, 4, 5, 6, 7])

In [37]:
randArr=np.random.default_rng(seed=10)
randArr2=randArr.integers(0,10,(4,5))
randArr2

array([[7, 9, 2, 2, 7],
       [8, 5, 1, 8, 5],
       [1, 1, 4, 6, 4],
       [8, 0, 4, 5, 9]], dtype=int64)

In [10]:
np.sort(randArr2,0)

array([[2, 0, 4, 0, 2],
       [5, 2, 6, 6, 2],
       [5, 6, 7, 8, 8],
       [7, 7, 9, 8, 9]], dtype=int64)

In [11]:
np.sort(randArr2,1)

array([[7, 7, 7, 8, 8],
       [2, 2, 5, 8, 9],
       [0, 2, 6, 6, 9],
       [0, 2, 4, 5, 6]], dtype=int64)

In [12]:
np.sort(randArr2)

array([[7, 7, 7, 8, 8],
       [2, 2, 5, 8, 9],
       [0, 2, 6, 6, 9],
       [0, 2, 4, 5, 6]], dtype=int64)

In [65]:
lst=randArr.integers(0,10,(4,6))
lst

array([[7, 0, 8, 6, 6, 2],
       [7, 4, 7, 7, 5, 5],
       [4, 0, 6, 0, 8, 3],
       [6, 8, 8, 2, 3, 4]], dtype=int64)

In [66]:
np.partition(lst,3,1)

array([[0, 2, 6, 6, 7, 8],
       [5, 5, 4, 7, 7, 7],
       [0, 3, 0, 4, 8, 6],
       [2, 4, 3, 6, 8, 8]], dtype=int64)

In [78]:
a=randArr.random((10,2))
print(a)
a[:,1]

[[0.24387851 0.60909837]
 [0.95701075 0.34488861]
 [0.14009266 0.8836421 ]
 [0.48760857 0.59041843]
 [0.7357258  0.08673739]
 [0.22608279 0.71864611]
 [0.83812164 0.36259294]
 [0.50873881 0.95336618]
 [0.64322034 0.98558556]
 [0.74853331 0.64825847]]


array([0.60909837, 0.34488861, 0.8836421 , 0.59041843, 0.08673739,
       0.71864611, 0.36259294, 0.95336618, 0.98558556, 0.64825847])