In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5])

In [3]:
arr>3

array([False, False, False,  True,  True])

In [4]:
arr!=5

array([ True,  True,  True,  True, False])

In [6]:
arr<4

array([ True,  True,  True, False, False])

In [8]:
(arr*2)<5

array([ True,  True, False, False, False])

In [11]:
(arr*2)!=(arr/2)

array([ True,  True,  True,  True,  True])

In [27]:
rng=np.random.default_rng(seed=231)
arr=rng.integers(10,size=(4,3))
arr

array([[2, 5, 1],
       [8, 4, 1],
       [1, 4, 0],
       [5, 8, 4]], dtype=int64)

In [18]:
np.count_nonzero(arr<6) #number of true values False=0 and True=1

10

In [19]:
np.sum(arr<6)

10

In [20]:
# how many values are less than 6 in each row 
np.sum(arr<6,axis=1)

array([3, 2, 3, 2])

In [ ]:
np.any(arr>11) #are there any values greater than 11

False

In [ ]:
np.all(arr<0) #are there any values less than 0

False

In [26]:
np.sum((arr>1) & (arr<4))

3

In [27]:
arr>1

array([[ True,  True, False],
       [ True,  True,  True],
       [ True, False,  True],
       [ True,  True, False]])

In [28]:
arr<4

array([[False, False,  True],
       [ True, False, False],
       [ True,  True,  True],
       [False, False,  True]])

In [29]:
~(arr<4)

array([[ True,  True, False],
       [False,  True,  True],
       [False, False, False],
       [ True,  True, False]])

In [30]:
(arr<3) | ~(arr<3)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [28]:
arr[arr<5]

array([2, 1, 4, 1, 1, 4, 0, 4], dtype=int64)

In [29]:
arr

array([[2, 5, 1],
       [8, 4, 1],
       [1, 4, 0],
       [5, 8, 4]], dtype=int64)

In [37]:
arr[arr>5] 

array([8, 8], dtype=int64)

In [6]:
A=np.array([1,2,3,4,5])
B=np.array([5,6,7,8,9])


# A and B
A&B

array([1, 2, 3, 0, 1])

In [7]:
A|B

array([ 5,  6,  7, 12, 13])