## Structured Data

In [1]:
import numpy as np

In [2]:
np.zeros(4)

array([0., 0., 0., 0.])

In [3]:
np.zeros(4,dtype=int)

array([0, 0, 0, 0])

In [25]:
data=np.zeros(4,dtype={'names':['name','age','weight'],
                  'formats':['U10','i4','f8']})

In [13]:
data

array([('', 0, 0.), ('', 0, 0.), ('', 0, 0.), ('', 0, 0.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [14]:
data.dtype

dtype([('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [54]:
name=['alice','bob','cathy','john']
age=[25,35,53,43]
weight=[65,76,67,87]

data['name']=name
data['age']=age
data['weight']=weight

In [16]:
data

array([('alice', 25, 65.), ('bob', 35, 76.), ('cathy', 53, 67.),
       ('john', 43, 87.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [17]:
type(data)

numpy.ndarray

In [18]:
type(data.all)

builtin_function_or_method

In [19]:
type(data[0])

numpy.void

In [20]:
data['name']

array(['alice', 'bob', 'cathy', 'john'], dtype='<U10')

In [21]:
data[-1]

('john', 43, 87.)

In [22]:
data[-1]['name']

'john'

In [23]:
data[data['age']<30]['name']

array(['alice'], dtype='<U10')

In [26]:
np.dtype({'names':['name','age','weight'],
      'formats':['U10','i4','f8']})

dtype([('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [27]:
np.dtype({
    'names':('name','age','weight'),
    'formats':((np.str_,10),int,np.float32)
})

dtype([('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

In [28]:
np.dtype('S10,i4,f8')

dtype([('f0', 'S10'), ('f1', '<i4'), ('f2', '<f8')])

In [47]:
tp=np.dtype([('id','i8'),('mat','f8',(3,1))])

In [48]:
tp

dtype([('id', '<i8'), ('mat', '<f8', (3, 1))])

In [49]:
x=np.zeros(1,dtype=tp)
print(x[0])
print(x['mat'][0])

(0, [[0.], [0.], [0.]])
[[0.]
 [0.]
 [0.]]


In [50]:
x

array([(0, [[0.], [0.], [0.]])],
      dtype=[('id', '<i8'), ('mat', '<f8', (3, 1))])

In [51]:
x['id']

array([0], dtype=int64)

In [52]:
x['mat']

array([[[0.],
        [0.],
        [0.]]])

In [55]:
data['age']

array([25, 35, 53, 43])

In [56]:
data_rec=data.view(np.recarray)

In [57]:
data_rec

rec.array([('alice', 25, 65.), ('bob', 35, 76.), ('cathy', 53, 67.),
           ('john', 43, 87.)],
          dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [58]:
data_rec.age

array([25, 35, 53, 43])

In [59]:
%timeit data['age']

74.7 ns ± 0.78 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
