In [1]:
import numpy as np

In [ ]:
np.arange(5)/np.arange(1,6)

array([0, 1, 2, 3, 4])

In [5]:
x=np.arange(9).reshape((3,3))
type(x)

numpy.ndarray

In [5]:
x=np.arange(5)
print("x+5= ",x+5)
print("x-5= ",x-5)
print("x*5= ",x*5)
print("x/5= ",x/5)
print("x //5= ",x//5)

x+5=  [5 6 7 8 9]
x-5=  [-5 -4 -3 -2 -1]
x*5=  [ 0  5 10 15 20]
x/5=  [0.  0.2 0.4 0.6 0.8]
x //5=  [0 0 0 0 0]


In [6]:
print("-x= ",-x)
print("x**2= ",x**2)
print("x%2= ",x%2)

-x=  [ 0 -1 -2 -3 -4]
x**2=  [ 0  1  4  9 16]
x%2=  [0 1 0 1 0]


In [9]:
print("(x**0.5)+(x*x)-(x**0.5)= ",(x**0.5)+(x*x)-(x**0.5))

(x**0.5)+(x*x)-(x**0.5)=  [ 0.  1.  4.  9. 16.]


In [14]:
y=np.arange(2,4)
print(y)
print(np.add(y,10))
print(y)

[2 3]
[12 13]
[2 3]


In [6]:
# absolute value 
arr=np.array((1,-2,3,4,5,6))
print(arr)
arr=-arr
print(arr)

[ 1 -2  3  4  5  6]
[-1  2 -3 -4 -5 -6]


In [7]:
print(np.abs(arr))

[1 2 3 4 5 6]


In [18]:
print(np.absolute(arr))

[1 2 3 4 5 6]


In [19]:
# trigonometric functions 
theta=np.linspace(0,np.pi,3)
print(theta)

[0.         1.57079633 3.14159265]


In [22]:
print("sin: ",np.sin(theta))
print("arctan: ",np.arctan(theta))

sin:  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
arctan:  [0.         1.00388482 1.26262726]


In [23]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__git_version__',
 '__loader__',

In [ ]:
# exponents 
x = [1, 2, 3]
print("x   =", x)
print("e^x =", np.exp(x))
print("2^x =", np.exp2(x))
print("3^x =", np.power(3., x))

x   = [1, 2, 3]
e^x = [ 2.71828183  7.3890561  20.08553692]
2^x = [2. 4. 8.]
3^x = [ 3.  9. 27.]


In [ ]:
# logarithms
x = [1, 2, 4, 10]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

x        = [1, 2, 4, 10]
ln(x)    = [0.         0.69314718 1.38629436 2.30258509]
log2(x)  = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


In [28]:
x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1 =", np.expm1(x))
print("log(1 + x) =", np.log1p(x))

exp(x) - 1 = [0.         0.0010005  0.01005017 0.10517092]
log(1 + x) = [0.         0.0009995  0.00995033 0.09531018]


In [29]:
import scipy
dir(scipy)

['LowLevelCallable',
 '__version__',
 'cluster',
 'constants',
 'datasets',
 'differentiate',
 'fft',
 'fftpack',
 'integrate',
 'interpolate',
 'io',
 'linalg',
 'ndimage',
 'odr',
 'optimize',
 'show_config',
 'signal',
 'sparse',
 'spatial',
 'special',
 'stats',
 'test']

In [33]:
x=np.arange(1,6)


In [9]:
np.add.reduce(x)

array([ 9, 12, 15])

In [10]:
np.multiply.reduce(x)

array([ 0, 28, 80])

In [11]:
np.add.accumulate(x)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]])

In [12]:
np.multiply.accumulate(x)

array([[ 0,  1,  2],
       [ 0,  4, 10],
       [ 0, 28, 80]])

In [13]:
x = np.arange(1, 6)
np.multiply.outer(x, x)
# 1*1,1*2,1*3,1*4,1*5,...

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])