In [1]:
import numpy as np

In [4]:
np.zeros(10,dtype='int64')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [ ]:
arr=np.random.default_rng(seed=1200)
x1=arr.integers(10,size=6)
x2=arr.integers(10,size=(3,5))
x3=arr.integers(10,size=(5,5,5))
x3

array([[[0, 2, 2, 1, 0],
        [5, 0, 8, 1, 6],
        [9, 8, 8, 9, 1],
        [6, 4, 2, 8, 5],
        [2, 3, 3, 4, 6]],

       [[6, 2, 5, 9, 2],
        [0, 3, 9, 1, 0],
        [9, 3, 9, 9, 1],
        [4, 2, 7, 6, 2],
        [3, 8, 9, 0, 8]],

       [[6, 2, 4, 7, 7],
        [5, 8, 2, 0, 5],
        [2, 5, 7, 5, 4],
        [6, 9, 4, 7, 9],
        [0, 0, 0, 3, 9]],

       [[0, 2, 7, 8, 4],
        [4, 2, 3, 0, 9],
        [3, 8, 8, 9, 0],
        [9, 5, 8, 5, 1],
        [9, 4, 1, 3, 5]],

       [[2, 8, 4, 0, 3],
        [0, 4, 5, 9, 7],
        [6, 7, 2, 4, 6],
        [3, 4, 0, 3, 4],
        [5, 3, 0, 5, 7]]], dtype=int64)

In [18]:
x3.ndim
x3.shape
x3.size
# x3.dtype

125

In [23]:
x1

array([7, 5, 4, 0, 5, 6], dtype=int64)

In [20]:
x1[0]

7

In [22]:
x1[-1]

6

In [25]:
x2[0]

array([5, 1, 9, 3, 9], dtype=int64)

In [27]:
x2[0][2]

9

In [29]:
x2[-2][-1]

6

In [34]:
x2[-1,-2]

9

In [37]:
x2[0,0]='a'
x2

ValueError: invalid literal for int() with base 10: 'a'

In [39]:
x2[0,0]='5'
x2

array([[5, 1, 9, 3, 9],
       [3, 1, 3, 7, 6],
       [6, 7, 3, 9, 0]], dtype=int64)

In [95]:
x2[2,0]=3.14
x2

array([[5, 1, 9, 3, 9],
       [3, 3, 3, 7, 6],
       [3, 3, 3, 9, 0]], dtype=int64)

In [59]:
x1

array([7, 5, 4, 0, 5, 6], dtype=int64)

In [61]:
x1[:]

array([7, 5, 4, 0, 5, 6], dtype=int64)

In [63]:
x1[-1:]

array([6], dtype=int64)

In [65]:
x1[:2]

array([7, 5], dtype=int64)

In [67]:
x1[:5]

array([7, 5, 4, 0, 5], dtype=int64)

In [69]:
x1[::2]

array([7, 4, 5], dtype=int64)

In [71]:
x1[1::2]

array([5, 0, 6], dtype=int64)

In [73]:
x1[::-1]

array([6, 5, 0, 4, 5, 7], dtype=int64)

In [75]:
x2

array([[5, 1, 9, 3, 9],
       [3, 3, 3, 7, 6],
       [3, 3, 3, 9, 0]], dtype=int64)

In [77]:
x2[1:4,1:4]

array([[3, 3, 7],
       [3, 3, 9]], dtype=int64)

In [79]:
x2[::-1,::-1]

array([[0, 9, 3, 3, 3],
       [6, 7, 3, 3, 3],
       [9, 3, 9, 1, 5]], dtype=int64)

In [81]:
x1

array([7, 5, 4, 0, 5, 6], dtype=int64)

In [83]:
x11=x1[::-1]

In [85]:
x11

array([6, 5, 0, 4, 5, 7], dtype=int64)

In [ ]:
x11[0]=999 #original array will be get modified

In [89]:
x1

array([  7,   5,   4,   0,   5, 999], dtype=int64)

In [91]:
# creating copies
x111=x1[::-1].copy()
x111

array([999,   5,   0,   4,   5,   7], dtype=int64)

In [92]:
x111[1]=-1111
x111

array([  999, -1111,     0,     4,     5,     7], dtype=int64)

In [94]:
x1 #original array will not be modified

array([  7,   5,   4,   0,   5, 999], dtype=int64)

In [98]:
# reshaping
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [100]:
arr=np.arange(1,10)

In [103]:
arr.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [105]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [116]:
arr.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [111]:
arr.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [113]:
arr[:,np.newaxis]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [115]:
arr[np.newaxis,:]

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [6]:
x=(1,2,3,4,5)
y=[6,7,8,9]

print(x)
print(type(x))
print(y)
print(type(y))

z=np.concatenate([x,y])
print(z)

(1, 2, 3, 4, 5)
<class 'tuple'>
[6, 7, 8, 9]
<class 'list'>
[1 2 3 4 5 6 7 8 9]


In [10]:
grid=[[1,2,3,4],[5,6,7,8]]
print(np.concatenate([grid,grid]))

[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]


In [16]:
print(np.concatenate([grid,grid],axis=1))

[[1 2 3 4 1 2 3 4]
 [5 6 7 8 5 6 7 8]]


In [24]:
arr=[[i+j for j in range(8)] for i in range(3)]
arr2=[[i-j for j in range(8)] for i in range(3)]

print(arr)
print(np.vstack([arr,arr2]))
print(np.hstack([arr,arr2]))



[[0, 1, 2, 3, 4, 5, 6, 7], [1, 2, 3, 4, 5, 6, 7, 8], [2, 3, 4, 5, 6, 7, 8, 9]]
[[ 0  1  2  3  4  5  6  7]
 [ 1  2  3  4  5  6  7  8]
 [ 2  3  4  5  6  7  8  9]
 [ 0 -1 -2 -3 -4 -5 -6 -7]
 [ 1  0 -1 -2 -3 -4 -5 -6]
 [ 2  1  0 -1 -2 -3 -4 -5]]
[[ 0  1  2  3  4  5  6  7  0 -1 -2 -3 -4 -5 -6 -7]
 [ 1  2  3  4  5  6  7  8  1  0 -1 -2 -3 -4 -5 -6]
 [ 2  3  4  5  6  7  8  9  2  1  0 -1 -2 -3 -4 -5]]


In [28]:
x=[1,2,3,4,5,6,7,8,9]
x1,x2,x3=np.split(x,[2,4])
print(x1,x2,x3)

[1 2] [3 4] [5 6 7 8 9]


In [35]:
y=np.arange(16).reshape([4,4])
print(y)

u,l=np.hsplit(y,[2])
print(u,"\n\n",l)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]] 

 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [36]:
u,l=np.vsplit(y,[2])
print(u,"\n\n",l)

[[0 1 2 3]
 [4 5 6 7]] 

 [[ 8  9 10 11]
 [12 13 14 15]]
