In [2]:
import numpy as np

In [7]:
lst=[1,2,3,4,5]
arr=np.array(lst)
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [13]:
lst2=['1','2',3,3.5,5]
arr2=np.array(lst2)
print(arr2)
print(type(arr2))
print([type(i) for i in lst2])
print([type(arr2[i]) for i in range(len(arr2))])

['1' '2' '3' '3.5' '5']
<class 'numpy.ndarray'>
[<class 'str'>, <class 'str'>, <class 'int'>, <class 'float'>, <class 'int'>]
[<class 'numpy.str_'>, <class 'numpy.str_'>, <class 'numpy.str_'>, <class 'numpy.str_'>, <class 'numpy.str_'>]


In [16]:
lst3=[2.3,3,4,5,6]
arr3=np.array(lst3)
print(arr3)
print([type(i) for i in lst3])
print([type(i) for i in arr3])

[2.3 3.  4.  5.  6. ]
[<class 'float'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>]
[<class 'numpy.float64'>, <class 'numpy.float64'>, <class 'numpy.float64'>, <class 'numpy.float64'>, <class 'numpy.float64'>]


In [20]:
arr4=np.array(lst3,dtype='int64')
print(arr4)

[2 3 4 5 6]


In [27]:
print(np.array(range(1,5)))

arr5=np.array([range(i,i+5) for i in [2,3,4,5]])
print(arr5)

[1 2 3 4]
[[2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]
 [5 6 7 8 9]]
